{{}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  namespace: {{ include "nats.namespace" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations}}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
spec:
  selector:
    {{}}
  clusterIP: None
  publishNotReadyAddresses: true
  {{}}
  {{}}
  ports:
  - name: {{ .Values.nats.client.portName }}
    port: {{ .Values.nats.client.port }}

  - name: cluster
    port: 6222