{{- if (include "redis-cluster.createStatefulSet" .) }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}

spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.cluster.nodes }}
  serviceName: {{ include "common.names.fullname" . }}-headless

  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}

    spec:
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: {{ include "redis-cluster.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          ports:
            - name: tcp-redis
              containerPort: {{ .Values.redis.containerPorts.redis }}
            - name: tcp-redis-bus
              containerPort: {{ .Values.redis.containerPorts.bus }}

          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.persistence.path }}
              subPath: {{ .Values.persistence.subPath }}
            - name: default-config
              mountPath: /opt/bitnami/redis/etc/redis-default.conf
              subPath: redis-default.conf
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/

      volumes:
        - name: scripts
          configMap:
            name: {{ include "common.names.fullname" . }}-scripts
            defaultMode: 0755

        - name: default-config
          configMap:
            name: {{ include "common.names.fullname" . }}-default

        - name: redis-tmp-conf
          emptyDir: {}


  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- include "common.storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}
        selector:
        {{- if .Values.persistence.matchLabels }}
          matchLabels:
          {{- toYaml .Values.persistence.matchLabels | nindent 12 }}
        {{- end -}}
{{- end }}
